#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          /home/cleber/open-control/backend/main.py
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start open-control at boot time 
# Description:       Open-control for controlling physical access to doors and gates 
### END INIT INFO

#echo "Waiting 1 seconds..."
#sleep 1
echo "Running at startup..."
cd /home/cleber/open-control/backend
python3 main.py &
echo "open-control API launched!"
